matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    when:
      event: [push, pull_request]
    image: rust
    environment:
      CARGO_TERM_COLOR: always
    commands:
      - rustup default $RUST
      - cargo check
      - cargo test
      - rustup component add clippy
      - cargo clippy -- -D warnings
      - cargo clippy --all-targets --all-features -- -D warnings
